remote_theme: "mmistakes/minimal-mistakes@4.15.1"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "dirt"
locale: "ko-KR"

title: "이것저것 기술 블로그"
title_separator: " - "
name: "Lian"
description: "매일 배운 것을 기록하면 좋겠다"
url: "https://github.com/kirseia"
baseurl: ""

# teaser: 
# header:
# logo: 

search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
